name: SatyamYoga
description: Traditional and Authentic Yoga!!!

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_email_sender: ^3.0.1
  # mailer: ^3.0.4
  # cloud_firestore: ^0.13.4
  url_launcher: ^5.4.10
  responsive_builder: ^0.2.0+2
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bluepattern.jpg
    - assets/childYoga.jpg
    - assets/client1.jpg
    - assets/client2.jpg
    - assets/corporateYoga.jpg
    - assets/facebook.png
    - assets/groupYoga.jpg
    - assets/hathaYoga.jpg
    - assets/instagram.png
    - assets/lotusbloom.jpg
    - assets/meditation.jpg
    - assets/privateYoga.jpg
    - assets/twitter.png
    - assets/yoga_class1.jpg
    - assets/yoga_class2.jpg
    - assets/yoga_class3.jpg
    - assets/yoga_logo.png
    - assets/tag.png


